M48
; DRILL file {KiCad (6.0.11)} date Thu Jun 15 09:24:01 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-15T09:24:01+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X106.0Y-36.0
X106.0Y-94.0
X186.099Y-36.234
X186.099Y-94.234
T0
M30
