M48
; DRILL file {KiCad (6.0.11)} date Thu Jun 15 16:04:23 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-15T16:04:23+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X106.0Y-25.0
X106.0Y-106.0
X187.0Y-25.0
X187.0Y-106.0
T0
M30
